# Generated by Django 3.0 on 2019-12-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banner/', verbose_name='Imagem')),
                ('banner_titulo', models.CharField(max_length=20, verbose_name='Título')),
                ('banner_descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='MVV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao_texto', models.TextField(max_length=200, verbose_name='Texto para descrever a missão da empresa')),
                ('visao_texto', models.TextField(max_length=200, verbose_name='Texto para descrever a visão da empresa')),
                ('valor_texto', models.TextField(max_length=200, verbose_name='Texto para descrever os valores da empresa')),
            ],
            options={
                'verbose_name': 'MVV',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico_tipo', models.TextField(verbose_name='Texto para o nome do serviço')),
                ('servico_descricao', models.TextField(verbose_name='Texto para descrever o serviço')),
                ('servico_icone', models.ImageField(upload_to='', verbose_name='Ícone correspondente ao serviço')),
            ],
            options={
                'verbose_name': 'Servicos',
            },
        ),
    ]
