# Generated by Django 2.2.7 on 2019-11-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MVV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao_texto', models.TextField(max_length=200, verbose_name='Texto para descrever a missão da empresa')),
                ('visao_texto', models.TextField(max_length=200, verbose_name='Texto para descrever a visão da empresa')),
                ('valor_texto', models.TextField(max_length=200, verbose_name='Texto para descrever os valores da empresa')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
    ]
