# Generated by Django 2.2.7 on 2019-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(default='banner/default.jpg', upload_to='banner/')),
                ('banner_titulo', models.CharField(max_length=20, verbose_name='Título que irá aparecer em laranja')),
                ('banner_descricao', models.CharField(max_length=50, verbose_name='Texto de descrição')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'MVV', 'verbose_name_plural': 'MVV'},
        ),
    ]
