# Generated by Django 2.2.7 on 2019-12-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'MVV', 'verbose_name_plural': 'MVV'},
        ),
    ]
