# Generated by Django 2.2.7 on 2019-12-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191201_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'MVV'},
        ),
    ]
