# Generated by Django 2.2.7 on 2019-12-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191202_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_titulo',
            field=models.CharField(max_length=20, verbose_name='Título'),
        ),
    ]
