# Generated by Django 3.0 on 2019-12-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191201_1451'),
        ('core', '0002_auto_20191201_1702'),
    ]

    operations = [
    ]
