# Generated by Django 2.2.7 on 2019-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191202_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(default='banner/default.jpg', upload_to='media/'),
        ),
    ]
