# Generated by Django 2.2.7 on 2019-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191202_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to='banner/', verbose_name='Imagem'),
        ),
    ]
